### ISSUE TITLE
Aspecte Generale

### ISSUE THREAD

**Issue by msimu** [greeneye256/Atm#4]
E super ca ai facut codul sa mearga!!!!!

Foloseste packete, nu pune tot codul intr-un singur loc (fara package)
Pune un pachet de baza si sub-pachete
Imparte codul de Holder in pachet de `holder`, codul Atm in pachet `atm`

**Comment by greeneye256** [comment]
Bai dar pe tine chiar te duce mintea!!!
Fain. Mersi mult, bre. 😜
